---
- name: Add repository
  apt_repository:
    repo: 'deb [trusted=yes] https://apt.fury.io/caddy/ /'
    state: present
    filename: caddy
- name: Ensure Caddy is installed
  apt:
    pkg: 'caddy'
    state: latest
- name: Ensure caddy etc directory exists
  file:
    path: /etc/caddy
    state: directory
- name: Ensure Caddyfile is here
  file:
    path: /etc/caddy/Caddyfile
    state: touch
- name: Reread Systemd config
  systemd:
    daemon_reload: yes
- name: Start Caddy service
  systemd:
    name: caddy
    state: started
    enabled: yes
