---
- name: Ensure ruby and YUI are installed
  apt:
    pkg: "{{item}}"
    state: latest
  with_items:
   - ruby
   - ruby-dev
   - yui-compressor
- name: Ensure SASS / COMPASS / LESS etc ... are here
  become: yes
  gem:
    name: "{{item}}"
    state: latest
  with_items:
   - chunky_png
   - multi_json
   - rb-fsevent
   - compass-core
   - compass-import-once
   - compass
   - sass
   - less