---
- name: Ensure the key is present
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.2.asc
- name: Add repository
  apt_repository:
    repo: 'deb http://repo.mongodb.org/apt/debian {{ ansible_distribution_release }}/mongodb-org/4.2 main'
    state: present
    filename: mongodb
- name: Update apt
  apt:
    update_cache: yes
- name: Ensure mongo is installed
  apt:
    pkg: mongodb-org
    state: latest
- name: Reread Systemd config
  systemd:
    daemon_reload: yes
- name: Start Mongo service
  systemd:
    name: mongod
    state: started
    enabled: yes
