---
- name: Create the SSH directory.
  file:
    state: directory
    path: "/home/{{user}}/.ssh/"
- name: Add this computer's RSA key to the remote host
  authorized_key:
    user: "{{user}}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"