---
  - name: Ensure the key is present
    apt_key:
      url: https://packages.elastic.co/GPG-KEY-elasticsearch
  - name: Add repository
    copy:
      src: elk.list
      dest: "/etc/apt/sources.list.d/elk.list"
    notify:
    - Update apt
  - name: Ensure kibana is installed
    apt:
      pkg: kibana
      state: latest
  - name: Ensure kibana is reloaded
    service: 
      name: kibana
      state: restarted
  - name: Ensure kibana starts at boot
    service: 
      name: kibana
      enabled: yes
  - name: Write /etc/kibana/kibana.yml 
    copy:
      src: kibana.yml
      dest: "/etc/kibana/kibana.yml"
  - name: Ensure kibana nginx conf is here
    copy:
      src: kibana.conf
      dest: /etc/nginx/available/kibana.conf
  - name: Write server_name
    lineinfile:
      dest: /etc/nginx/available/kibana.conf
      state: present
      regexp: '  server_name           '
      line: "  server_name           {{ monitoring_server }};"
  - name: Ensure kibana nginx conf is enabled
    file:
      src: "/etc/nginx/available/kibana.conf"
      dest: "/etc/nginx/enabled/kibana.conf"
      state: link
  - name: Ensure python-passlib is installed
    apt:
      name: python-passlib
      state: present
  - name: Create htpasswd
    htpasswd:
      path: /etc/nginx/available/kibana.htpasswd
      name: "{{ user }}"
      password: "{{ htpasswd }}"
      owner: root
      group: www-data
      mode: 0640