---
- name: Ensure php GPG key is present (Ondrej Sury)
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
- name: Add repository
  apt_repository:
    repo: 'deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main'
    state: present
    filename: "php{{ php_version }}"
- name: Ensure php-fpm + libs is installed
  apt:
    pkg: ["php{{ php_version }}", "php{{ php_version }}-fpm", "php{{ php_version }}-cli", "php{{ php_version }}-mysql", "php{{ php_version }}-pgsql", "php{{ php_version }}-intl", "php{{ php_version }}-curl", "php{{ php_version }}-gd", "php{{ php_version }}-mbstring", "php{{ php_version }}-xml", "php{{ php_version }}-bcmath", "php{{ php_version }}-zip", "php{{ php_version }}-imagick"]
    state: latest
- name: "[PHP 7.X ONLY] Install legacy packages"
  apt:
    pkg: ["php{{ php_version }}-json"]
    state: latest
  when: "php_version.startswith('7.')"
- name: Writes the correct version of the ini configuration (fpm)
  copy:
    src: php.ini
    dest: "/etc/php/{{ php_version }}/fpm/php.ini"
- name: Add correct timezone (cli)
  lineinfile:
    dest: /etc/php/{{ php_version }}/cli/php.ini
    line: 'date.timezone = "Europe/Paris"'
    state: present
    insertafter: "^[Date]"
- name: Writes the correct version of the configuration
  copy:
    src: php-fpm.conf
    dest: "/etc/php/{{ php_version }}/fpm/php-fpm.conf"
- name: Replaces the version of php in the configuration file
  replace:
    path: "/etc/php/{{ php_version }}/fpm/php-fpm.conf"
    regexp: '7\.4'
    replace: "{{ php_version }}"
- name: Ensure the log folder is here
  file:
    path: /var/log/php-fpm
    state: directory
    owner: root
    group: adm
- name: Writes the correct version of the pool
  copy:
    src: www.conf
    dest: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
- name: Start php-fpm
  service:
    name: "php{{ php_version }}-fpm"
    state: restarted
    daemon_reload: yes
    enabled: yes
- name: Add debian to www-data group
  user:
    name: debian
    groups: www-data
    append: yes
- name: Download composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/installer
- name: Install composer
  shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
  args:
    creates: /usr/local/bin/composer
- name: Rename composer.phar to composer
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
  args:
    creates: /usr/local/bin/composer
- name: Make composer executable
  file:
    path: /usr/local/bin/composer
    mode: a+x
    state: file
