---

## 
## Install monitoring server configuration
##
- name: Install the monitoring config
  hosts: monitoring-servers
  remote_user: "{{user}}"
  sudo: yes

  roles:
    - git
    - nginx
    - elasticsearch
    - logstash
    - mongo
    - kibana

## 
## Install webserver configuration
##
- name: Install the base config for serving content
  hosts: front-servers
  remote_user: "{{user}}"
  sudo: yes

  roles:
    - nginx
    - supervisor
    - hhvm
    - node
    - maria_db
    - backup
    - logstash
# Other available roles :
#   - mongo

  tasks:
    - name: Ensure the web folder is here
      file:
        path: "/home/{{user}}/www"
        state: directory
        group: www-data
        owner: "{{user}}"

## 
## Install deployment server configuration
##
- name: Install the base config for deployment
  hosts: deploy-servers
  remote_user: "{{user}}"
  sudo: yes

  roles:
    - git
    - php-cli
    - ruby
    - node
    - brad

  tasks:
    - name: Ensure the deploy folder is here
      file:
        path: "/home/{{user}}/deploy"
        state: directory
        owner: "{{user}}"
        group: www-data
    - name: Ensure the release folder is here
      file:
        path: "/home/{{user}}/release"
        state: directory
        owner: "{{user}}"
        group: www-data

## 
## Cleans up
##
- name: Cleans up password files
  hosts: 127.0.0.1
  connection: local
  sudo: yes

  tasks:
    - name: Delete tmp passwords
      shell: "rm -f /tmp/ansible.password.*"
      ignore_errors: True
    - name: Say done
      debug:
        msg: "Done."



