---
- name: Provision NodeJS frontend servers
  hosts: frontend_node
  become: yes

  roles:
    - base
    - caddy
    - node
    - yarn

  tasks:
    - name: Ensure the web folder is here
      file:
        path: "/var/www"
        state: directory
        group: "{{ ansible_user }}"
        owner: "{{ ansible_user }}"
